name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17 # Use Java 17 here because the Loom test env needs it
          distribution: temurin

      - name: Cache Gradle files
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/build.gradle', '*/settings.gradle', '*gradle.*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build
        env:
          EXCLUDE_SUBPROJECTS: true

      - name: Release Build
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          EXCLUDE_SUBPROJECTS: true
